//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizationGenerator.Languages {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizationGenerator.Languages.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Autor: Mateusz Nejman.
        /// </summary>
        internal static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odtwarzacz umożliwia słuchanie muzyki z youtube, oraz lokalnie. Autor nie ponosi odpowiedzialności za to, w jaki sposób użytkownik używa mediów z podanych serwisów..
        /// </summary>
        internal static string AboutDesc {
            get {
                return ResourceManager.GetString("AboutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strona autora.
        /// </summary>
        internal static string AboutWWW {
            get {
                return ResourceManager.GetString("AboutWWW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodać tagi?.
        /// </summary>
        internal static string AddTags {
            get {
                return ResourceManager.GetString("AddTags", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wykonawca.
        /// </summary>
        internal static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wykonawcy.
        /// </summary>
        internal static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Automatycznie konwertuj do mp3.
        /// </summary>
        internal static string AutoConvert {
            get {
                return ResourceManager.GetString("AutoConvert", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy chcesz automatycznie aktualizować pobrane playlisty?.
        /// </summary>
        internal static string AutoDownload {
            get {
                return ResourceManager.GetString("AutoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Naciśnij jeszcze raz, aby wyjść.
        /// </summary>
        internal static string BackPressed {
            get {
                return ResourceManager.GetString("BackPressed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Anuluj.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień nazwę.
        /// </summary>
        internal static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz playlistę.
        /// </summary>
        internal static string ChoosePlaylist {
            get {
                return ResourceManager.GetString("ChoosePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyczyść.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Połącz.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Konwersja.
        /// </summary>
        internal static string Conversion {
            get {
                return ResourceManager.GetString("Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pliki wejściowe.
        /// </summary>
        internal static string ConversionInputFiles {
            get {
                return ResourceManager.GetString("ConversionInputFiles", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Folder wyjściowy.
        /// </summary>
        internal static string ConversionOutputFolder {
            get {
                return ResourceManager.GetString("ConversionOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Format wyjściowy.
        /// </summary>
        internal static string ConversionOutputFormat {
            get {
                return ResourceManager.GetString("ConversionOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Konwertuj.
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okładka.
        /// </summary>
        internal static string Cover {
            get {
                return ResourceManager.GetString("Cover", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wczytaj okładkę.
        /// </summary>
        internal static string CoverLoad {
            get {
                return ResourceManager.GetString("CoverLoad", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz okładkę.
        /// </summary>
        internal static string CoverSave {
            get {
                return ResourceManager.GetString("CoverSave", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rozłącz.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik jest uszkodzony.
        /// </summary>
        internal static string FileCorrupted {
            get {
                return ResourceManager.GetString("FileCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pobrano.
        /// </summary>
        internal static string FileDownloaded {
            get {
                return ResourceManager.GetString("FileDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Folder nie istnieje.
        /// </summary>
        internal static string FolderExists {
            get {
                return ResourceManager.GetString("FolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Informacje.
        /// </summary>
        internal static string Informations {
            get {
                return ResourceManager.GetString("Informations", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Instrukcja.
        /// </summary>
        internal static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu English.
        /// </summary>
        internal static string LanguageEN {
            get {
                return ResourceManager.GetString("LanguageEN", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Polski.
        /// </summary>
        internal static string LanguagePL {
            get {
                return ResourceManager.GetString("LanguagePL", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Русский.
        /// </summary>
        internal static string LanguageRU {
            get {
                return ResourceManager.GetString("LanguageRU", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ostatnio odtwarzane.
        /// </summary>
        internal static string LastViews {
            get {
                return ResourceManager.GetString("LastViews", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Biblioteka.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strona główna.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Najczęściej odtwarzane.
        /// </summary>
        internal static string MostViews {
            get {
                return ResourceManager.GetString("MostViews", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nowa playlista.
        /// </summary>
        internal static string NewPlaylist {
            get {
                return ResourceManager.GetString("NewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wprowadź nazwę playlisty.
        /// </summary>
        internal static string NewPlaylistHint {
            get {
                return ResourceManager.GetString("NewPlaylistHint", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dalej.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak dostępu do internetu.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak pobierania w toku.
        /// </summary>
        internal static string NoDownloads {
            get {
                return ResourceManager.GetString("NoDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przyznaj uprawnienia.
        /// </summary>
        internal static string PermissionGrant {
            get {
                return ResourceManager.GetString("PermissionGrant", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odtwarzacz wymaga uprawnień do zapisu danych po to, aby móc pobierać muzykę oraz zapisywać ustawienia.
        /// </summary>
        internal static string PermissionInfo {
            get {
                return ResourceManager.GetString("PermissionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Playlista.
        /// </summary>
        internal static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utworzyć nową playlistę z pobranymi utworami?.
        /// </summary>
        internal static string PlaylistDownload {
            get {
                return ResourceManager.GetString("PlaylistDownload", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Istnieje już playlista z taką nazwą.
        /// </summary>
        internal static string PlaylistExists {
            get {
                return ResourceManager.GetString("PlaylistExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pobrać playlistę czy utwór?.
        /// </summary>
        internal static string PlaylistOrTrack {
            get {
                return ResourceManager.GetString("PlaylistOrTrack", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odtwórz.
        /// </summary>
        internal static string PlaylistPlay {
            get {
                return ResourceManager.GetString("PlaylistPlay", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Playlisty.
        /// </summary>
        internal static string Playlists {
            get {
                return ResourceManager.GetString("Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Postęp.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pytanie.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usunąć plik.
        /// </summary>
        internal static string QuestionDelete {
            get {
                return ResourceManager.GetString("QuestionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu z playlisty.
        /// </summary>
        internal static string QuestionDeleteFromPlaylist {
            get {
                return ResourceManager.GetString("QuestionDeleteFromPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usunąć playlistę.
        /// </summary>
        internal static string QuestionDeletePlaylist {
            get {
                return ResourceManager.GetString("QuestionDeletePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string QuestionDeletePlaylistg {
            get {
                return ResourceManager.GetString("QuestionDeletePlaylistg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gotowe.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odbierz.
        /// </summary>
        internal static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kod odbiorcy.
        /// </summary>
        internal static string ReceiverCode {
            get {
                return ResourceManager.GetString("ReceiverCode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zamień z istniejącymi plikami.
        /// </summary>
        internal static string ReplaceWithExists {
            get {
                return ResourceManager.GetString("ReplaceWithExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Szukaj.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Historia wyszukiwania.
        /// </summary>
        internal static string SearchHistory {
            get {
                return ResourceManager.GetString("SearchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyszukiwanie....
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do wyszukiwarki możesz wkleić link do utworu, playlisty, lub wpisać tytuł..
        /// </summary>
        internal static string SearchTip {
            get {
                return ResourceManager.GetString("SearchTip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz folder.
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyślij.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wygeneruj tagi dla plików lokalnych.
        /// </summary>
        internal static string Settings0 {
            get {
                return ResourceManager.GetString("Settings0", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Automatyczne tagi.
        /// </summary>
        internal static string Settings1 {
            get {
                return ResourceManager.GetString("Settings1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyczyść wszystkie dane.
        /// </summary>
        internal static string Settings2 {
            get {
                return ResourceManager.GetString("Settings2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ignoruj wyciszanie utworów podczas rozmowy.
        /// </summary>
        internal static string Settings3 {
            get {
                return ResourceManager.GetString("Settings3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj folder do listy skanowanych folderów.
        /// </summary>
        internal static string Settings4 {
            get {
                return ResourceManager.GetString("Settings4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Język.
        /// </summary>
        internal static string Settings5 {
            get {
                return ResourceManager.GetString("Settings5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmiany będą widoczne po ponownym uruchomieniu aplikacji.
        /// </summary>
        internal static string SettingsChanges {
            get {
                return ResourceManager.GetString("SettingsChanges", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyślnie usunięto.
        /// </summary>
        internal static string SnackDelete {
            get {
                return ResourceManager.GetString("SnackDelete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik nie istnieje.
        /// </summary>
        internal static string SnackFileExists {
            get {
                return ResourceManager.GetString("SnackFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodano do playlisty.
        /// </summary>
        internal static string SnackPlaylist {
            get {
                return ResourceManager.GetString("SnackPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodano do kolejki.
        /// </summary>
        internal static string SnackQueue {
            get {
                return ResourceManager.GetString("SnackQueue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj do wysłania.
        /// </summary>
        internal static string SyncAdd {
            get {
                return ResourceManager.GetString("SyncAdd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj do wysłania (playlista).
        /// </summary>
        internal static string SyncAddPlaylist {
            get {
                return ResourceManager.GetString("SyncAddPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 1. Podłącz urządzenia do tej samej sieci.
        /// </summary>
        internal static string SyncHelp1 {
            get {
                return ResourceManager.GetString("SyncHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 2. Wpisz kod lub poczekaj na połączenie.
        /// </summary>
        internal static string SyncHelp2 {
            get {
                return ResourceManager.GetString("SyncHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 2. Wpisz kod.
        /// </summary>
        internal static string SyncHelp2Desktop {
            get {
                return ResourceManager.GetString("SyncHelp2Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 3. Wybierz odpowiednią opcję.
        /// </summary>
        internal static string SyncHelp3 {
            get {
                return ResourceManager.GetString("SyncHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Synchronizacja z telefonem.
        /// </summary>
        internal static string SyncPhone {
            get {
                return ResourceManager.GetString("SyncPhone", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odbieranie plików.
        /// </summary>
        internal static string SyncReceiving {
            get {
                return ResourceManager.GetString("SyncReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wysyłanie plików.
        /// </summary>
        internal static string SyncSending {
            get {
                return ResourceManager.GetString("SyncSending", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pokaż pliki do wysłania.
        /// </summary>
        internal static string SyncShowFiles {
            get {
                return ResourceManager.GetString("SyncShowFiles", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ciemny.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Domyślny.
        /// </summary>
        internal static string ThemeDefault {
            get {
                return ResourceManager.GetString("ThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Różowy.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tytuł.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pobieranie.
        /// </summary>
        internal static string TitleDownloads {
            get {
                return ResourceManager.GetString("TitleDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utwór.
        /// </summary>
        internal static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisanych utworów.
        /// </summary>
        internal static string TrackCount {
            get {
                return ResourceManager.GetString("TrackCount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utworów.
        /// </summary>
        internal static string TrackCountPlaylist {
            get {
                return ResourceManager.GetString("TrackCountPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń.
        /// </summary>
        internal static string TrackMenuDelete {
            get {
                return ResourceManager.GetString("TrackMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj.
        /// </summary>
        internal static string TrackMenuEdit {
            get {
                return ResourceManager.GetString("TrackMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj do playlisty.
        /// </summary>
        internal static string TrackMenuPlaylist {
            get {
                return ResourceManager.GetString("TrackMenuPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj do kolejki.
        /// </summary>
        internal static string TrackMenuQueue {
            get {
                return ResourceManager.GetString("TrackMenuQueue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utwory.
        /// </summary>
        internal static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nieznany wykonawca.
        /// </summary>
        internal static string UnknownArtist {
            get {
                return ResourceManager.GetString("UnknownArtist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wypakowano.
        /// </summary>
        internal static string Unpacked {
            get {
                return ResourceManager.GetString("Unpacked", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Uwaga.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tak.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Twój kod.
        /// </summary>
        internal static string YourCode {
            get {
                return ResourceManager.GetString("YourCode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd spowodowany zmianami w serwisie YouTube. Proszę czekać na aktualizację uwzględniający podane zmiany..
        /// </summary>
        internal static string YoutubeError {
            get {
                return ResourceManager.GetString("YoutubeError", resourceCulture);
            }
        }
    }
}
